# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: docker build --target build -t hlbuildimage -f .devcontainer/Dockerfile . &&  docker run --name hlbuildcontainer hlbuildimage && docker cp hlbuildcontainer:/out $(Build.ArtifactStagingDirectory)/HLOutput
      displayName: Build high-level Azure Sphere application in a container and copy the output
    - task: PublishBuildArtifacts@1
      displayName: 'Publish AzureSphereBlink imagepackage'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/HLOutput/HelloWorld_RTApp_MT3620_BareMetal.imagepackage'
        ArtifactName: 'HelloWorld_RTApp_MT3620_BareMetal imagepackage'
